#!/usr/bin/env node
//
// Regenerate the Featured work block in README.md from live GitHub data.
//
//     node tools/refresh-readme.mjs           write README.md
//     node tools/refresh-readme.mjs --check   exit 1 if it would change
//
// Why this exists: the star count used to be typed into the README by hand, so
// it was wrong within a week. Everything here is fetched at build time and
// rendered to PLAIN MARKUP, so the profile has no third-party image service to
// depend on at view time. If this workflow ever stops running, the README stays
// exactly as it last was rather than filling with broken images.
//
// Node 20+, no dependencies.

import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const START = "<!-- FEATURED:START -->";
const END = "<!-- FEATURED:END -->";

const check = process.argv.includes("--check");

const cfg = JSON.parse(await readFile(join(ROOT, "featured.json"), "utf8"));
const minStars = cfg.minStars ?? 10;

// GITHUB_TOKEN is injected by Actions. Without it this still works, just against
// the much lower anonymous rate limit, which is fine for a handful of repos.
const headers = {
    "accept": "application/vnd.github+json",
    "user-agent": "refresh-readme",
    ...(process.env.GITHUB_TOKEN ? { authorization: `Bearer ${process.env.GITHUB_TOKEN}` } : {})
};

async function fetchRepo(owner, repo) {
    const r = await fetch(`https://api.github.com/repos/${owner}/${repo}`, { headers });
    if (!r.ok) throw new Error(`${owner}/${repo}: HTTP ${r.status} ${await r.text()}`);
    return r.json();
}

const rows = [];
for (const entry of cfg.repos) {
    const d = await fetchRepo(cfg.owner, entry.repo);

    // The repo's own description is the fallback, so a repo with no override
    // has exactly one place its wording lives.
    const blurb = entry.blurb ?? d.description ?? "";
    const name = entry.name ?? d.name;
    const url = d.html_url;

    // Only worth showing when it means something. A row of zeroes is worse
    // than no number.
    const stars = d.stargazers_count >= minStars
        ? ` <a href="${url}/stargazers">&#9733; ${d.stargazers_count}</a>`
        : "";

    rows.push(`<b><a href="${url}">${name}</a></b>: ${blurb}${stars}`);
    console.log(`  ${entry.repo.padEnd(34)} ${String(d.stargazers_count).padStart(4)} stars${stars ? "  (shown)" : ""}`);
}

const generated = [
    START,
    "<!-- Generated by tools/refresh-readme.mjs. Edit featured.json, not this. -->",
    "",
    '<p align="center">',
    rows.join("<br><br>\n"),
    "</p>",
    END
].join("\n");

const readmePath = join(ROOT, "README.md");
const readme = await readFile(readmePath, "utf8");

const s = readme.indexOf(START);
const e = readme.indexOf(END);
if (s === -1 || e === -1) {
    console.error(`FAIL  README.md is missing ${START} / ${END}`);
    process.exit(1);
}

const next = readme.slice(0, s) + generated + readme.slice(e + END.length);

if (next === readme) {
    console.log("\nno change");
    process.exit(0);
}
if (check) {
    console.error("\nREADME is out of date");
    process.exit(1);
}
await writeFile(readmePath, next);
console.log("\nREADME.md updated");
