#!/usr/bin/env node
//
// Regenerate the Featured work block in README.md from live GitHub data.
//
//     node tools/refresh-readme.mjs           write README.md
//     node tools/refresh-readme.mjs --check   exit 1 if it would change
//
// Why this exists: the star count used to be typed into the README by hand, so
// it was wrong within a week. Everything here is fetched at build time and
// rendered to PLAIN MARKUP, so the profile depends on no third-party image
// service at view time. If this workflow ever stops running the README stays
// exactly as it last was rather than filling with broken images.
//
// Layout is a two-column table per group: identity and metadata on the left,
// prose on the right. Left-aligned deliberately. The rest of the profile is
// centred, which suits a header and is hard work for a list of ten projects.
//
// Node 20+, no dependencies.

import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const START = "<!-- FEATURED:START -->";
const END = "<!-- FEATURED:END -->";

const check = process.argv.includes("--check");
const cfg = JSON.parse(await readFile(join(ROOT, "featured.json"), "utf8"));

// GITHUB_TOKEN is injected by Actions. Without it this still works, against the
// much lower anonymous rate limit, which is fine for a dozen repos.
const headers = {
    "accept": "application/vnd.github+json",
    "user-agent": "refresh-readme",
    ...(process.env.GITHUB_TOKEN ? { authorization: `Bearer ${process.env.GITHUB_TOKEN}` } : {})
};

async function fetchRepo(owner, repo) {
    const r = await fetch(`https://api.github.com/repos/${owner}/${repo}`, { headers });
    if (!r.ok) throw new Error(`${owner}/${repo}: HTTP ${r.status} ${(await r.text()).slice(0, 200)}`);
    return r.json();
}

const out = [];
let total = 0;

for (const group of cfg.groups) {
    out.push(`<h3>${group.heading}</h3>`, "", "| | |", "|:--|:--|");

    for (const entry of group.repos) {
        const owner = entry.owner ?? cfg.owner;
        const d = await fetchRepo(owner, entry.repo);

        // The repo's own description is the fallback, so a repo with no
        // override has exactly one place its wording lives.
        const blurb = entry.blurb ?? d.description ?? "";
        const name = entry.name ?? d.name;

        const meta = [];
        if (d.language) meta.push(`\`${d.language}\``);
        meta.push(`<a href="${d.html_url}/stargazers">&#9733; ${d.stargazers_count}</a>`);

        // Left cell: what it is called and what it is made of. Right cell: prose.
        out.push(`| **<a href="${d.html_url}">${name}</a>**<br><sub>${meta.join(" &middot; ")}</sub> | ${blurb} |`);

        total++;
        console.log(`  ${(owner + "/" + entry.repo).padEnd(46)} ${String(d.stargazers_count).padStart(4)} stars  ${d.language ?? "-"}`);
    }
    out.push("");
}

const generated = [
    START,
    "<!-- Generated by tools/refresh-readme.mjs. Edit featured.json, not this. -->",
    "",
    ...out
].join("\n").trimEnd() + "\n" + END;

const readmePath = join(ROOT, "README.md");
const readme = await readFile(readmePath, "utf8");

const s = readme.indexOf(START);
const e = readme.indexOf(END);
if (s === -1 || e === -1) {
    console.error(`FAIL  README.md is missing ${START} / ${END}`);
    process.exit(1);
}

const next = readme.slice(0, s) + generated + readme.slice(e + END.length);

console.log(`\n${total} repositories across ${cfg.groups.length} groups`);

if (next === readme) {
    console.log("no change");
    process.exit(0);
}
if (check) {
    console.error("README is out of date");
    process.exit(1);
}
await writeFile(readmePath, next);
console.log("README.md updated");
